<div class="container-divider"></div>
<section class="section-search">
  <div class="section-search__hero">
    <h2 class="hero-search">Hi. How can we help?</h2>
    <form class="search search-full" id="new_search_form" action="/catalogsearch/result/" method="get">
      <div class="field search">
        <div class="control">
          <input id="new-search" data-mage-init='{"quickSearch":{
                     "formSelector":"#new_search_form",
                     "minSearchLength": 1,
                     "url":"/search/ajax/suggest",
                     "destinationSelector":"#search_results"}
                    }' type="text" name="q" placeholder="<?= $block->escapeHtmlAttr(__('Search entire store here...')) ?>" class="input-text" />
          <div id="search_results" class="search-autocomplete"></div>
        </div>
      </div>
    </form>
  </div>
</section>

<div class="container">
  <section class="container__section">

    <section class="categories blocks">

      <ul class="blocks__list">
        <li class="blocks-item">
          <a href="" class="blocks-item__link">
            <h4 class="blocks-item__title">Magento 2 Pearl Theme User Guide</h4>
          </a>
        </li>

        <li class="blocks-item">
          <a href="" class="blocks-item__link">
            <h4 class="blocks-item__title">Magento 2 User Guide</h4>
          </a>
        </li>
      </ul>

    </section>

    <section class="articles">
      <h3>Promoted articles</h3>
      <ul class="article__list promoted-articles">

        <li class="promoted-articles__item">
          <a href="">
            How to Go Live with Magento 2 in less than 30 days using the Pearl Theme - 50 step guide [tutorial]
          </a>
        </li>

        <li class="promoted-articles__item">
          <a href="">
            How to use Pearl Theme on multiple store views. Important update / install instructions
          </a>
        </li>

        <li class="promoted-articles__item">
          <a href="">
            How to install the Pearl Theme on Magento Commerce Cloud - using UNIX systems
          </a>
        </li>

        <li class="promoted-articles__item">
          <a href="">
            How to install Pearl Responsive Theme - 1 minute installation GUI
          </a>
        </li>

        <li class="promoted-articles__item">
          <a href="">
            How to customize css / xml / phtml / js files in Magento 2 - examples [ Tutorial ]
          </a>
        </li>

        <li class="promoted-articles__item">
          <a href="">
            License key for local / staging / development environment. Multi-store licensing.
          </a>
        </li>

        <li class="promoted-articles__item">
          <a href="">
            How to debug: use WeltPixel Debugger and fix Magento 2 extension conflicts
          </a>
        </li>

        <li class="promoted-articles__item">
          <a href="">
            How can I extend the support period for my WeltPixel products?
          </a>
        </li>

        <li class="promoted-articles__item">
          <a href="">
            How can I upgrade/update the Pearl Theme to the latest version?
          </a>
        </li>

        <li class="promoted-articles__item">
          <a href="">
            Magento 2.4 &amp; Extension Development
          </a>
        </li>

        <li class="promoted-articles__item">
          <a href="">
            WeltPixel Product Updates - Change Log and New Releases
          </a>
        </li>

        <li class="promoted-articles__item">
          <a href="">
            Choosing the right Magento 2 hosting
          </a>
        </li>

      </ul>
    </section>
  </section>

  <section class="container__section community">
    <h2 class="title-support">
      Post a question.
      <br>
      Anybody can answer.
    </h2>
    <a class="community-link" href="">
      Join the conversation
    </a>
    <div class="community-image"></div>
  </section>
  <section class="container__section">
    <div class="conten-activity">
      <div class="conten-activity__recent">
        <h2 class="title-recent">Recent activity</h2>
        <ul class="activity-list">
          <li class="activity-list__item show" data-recent-activity-action="post_comment_added">

            <a class="activity-link" href="">GA4 plugin for Magento
              2 issue - Purchase event is not triggered</a>
            <div class="activity-meta">
              <div class="activity-meta__time">Comment added 17 hours ago</div>
              <div class="activity-meta__comment"><span>2</span></div>
            </div>
          </li>
          <li class="activity-list__item show" data-recent-activity-action="post_created">

            <a class="activity-link" href="">Product List widget not
              showing product images</a>
            <div class="activity-meta">
              <div class="activity-meta__time">Post created 21 hours ago</div>
              <div class="activity-meta__comment"><span>0</span></div>
            </div>
          </li>
          <li class="activity-list__item show" data-recent-activity-action="post_comment_added">

            <a class="activity-link" href="">GA4 Magento 2 extension
              - FPC Varnish issue with data pushed to datalayer</a>
            <div class="activity-meta">
              <div class="activity-meta__time">Comment added 2 days ago</div>
              <div class="activity-meta__comment"><span>2</span></div>
            </div>
          </li>
          <li class="activity-list__item show" data-recent-activity-action="post_comment_added">

            <a class="activity-link" href="">Customer Login,SignUp
              and LogOut Event not Found in Extension </a>
            <div class="activity-meta">
              <div class="activity-meta__time">Comment added 2 days ago</div>
              <div class="activity-meta__comment"><span>1</span></div>
            </div>
          </li>
          <li class="activity-list__item show" data-recent-activity-action="post_comment_added">

            <a class="activity-link" href="">Magento 2.4
              compatibility</a>
            <div class="activity-meta">
              <div class="activity-meta__time">Comment added 2 days ago</div>
              <div class="activity-meta__comment"><span>1</span></div>
            </div>
          </li>
          <li class="activity-list__item" data-recent-activity-action="post_comment_added">

            <a class="activity-link" href="">Magento 2.4
              compatibility</a>
            <div class="activity-meta">
              <div class="activity-meta__time">Comment added 2 days ago</div>
              <div class="activity-meta__comment"><span>1</span></div>
            </div>
          </li>
          <li class="activity-list__item" data-recent-activity-action="post_comment_added">

            <a class="activity-link" href="">Magento 2.4
              compatibility</a>
            <div class="activity-meta">
              <div class="activity-meta__time">Comment added 2 days ago</div>
              <div class="activity-meta__comment"><span>1</span></div>
            </div>
          </li>
        </ul>
        <div class="recent-activity-no-activities"></div>
        <div class="recent-activity-loader">...</div>
        <div class="recent-activity-controls" >
          <button href="#" onclick="showMoreRecentActivity()">See more</button>
        </div>
      </div>
    </div>
  </section>
</div>

<script>
  var recentActivityItems = document.querySelectorAll('.activity-list__item');
  var showMoreButton = document.querySelector('.recent-activity-controls button');
  var visibleItems = 5;
  var increment = 5;

  function showMoreRecentActivity() {
    visibleItems += increment;

    for (var i = 0; i < recentActivityItems.length; i++) {
      if (i < visibleItems) {
        recentActivityItems[i].classList.add('show');
      } else {
        recentActivityItems[i].classList.remove('show');
      }
    }

    if (visibleItems >= recentActivityItems.length) {
      showMoreButton.style.display = 'none';
    }
  }
</script>