<div data-mage-init='{
    "collapsible":{
        "openedState": "active",
        "active": [0],
        "animate":{ "duration" :1000, "easing":"easeOutCubic"}
    }}'>
    <div data-role="title" class="social-collapse">
        <strong>Login With Social Profile</strong>
    </div>

    <div data-role="content">
        <?php echo $this->getChildHtml('social-login-popup-authentication-social-login');?>
    </div>
</div>

