<div id="loaderSnipper" data-role="loader" class="loading-mask main-loader">

    <!--PARA TENER UN LOADER UTILIZANDO ALGUN GIF DESCOMENTA EL SIGUIENTE CODIGO.-->
    <div class="loader-image">
        <img src="<?php echo $this->getViewFileUrl('AgSoftware_LoaderSnipper::images/loader.gif') ?>" alt="Loader">
    </div>


    <!--PARA TENER UN LOADER UTILIZANDO ALGUN TEXTO DESCOMENTA EL SIGUIENTE CODIGO.-->
   <!--<div class="loader-text">
        <?php /*echo __('Cargando...') */?>
    </div>-->

    <!--PARA TENER UN LOADER UTILIZANDO ALGUNA ANIMACION DESCOMENTA EL SIGUIENTE CODIGO.-->
    <!--<div class="loader-animation">
        <div></div>
        <div></div>
        <div></div>
    </div>-->

</div>
