<div class="checkout-success">
    <p>
        Great news! Your order
        <strong>100058905</strong>
        is now confirmed and your products are ready for download under:
        <b>My Account &gt; Downloadable Products.
        </b>
    </p>
    <p>
        If you don't have an account yet, we just created one for you. Follow the instructions in the
        <b>
            Welcome Email
        </b>
        and set a password for it.
    </p>
</div>
