<div class="order-info">
    <div class="product-grid">
        <div class="table-wrapper order-items">
            <table class="data table table-order-items" id="table-order-items">
                <thead>
                <tr>
                    <th class="col image textalign-left">Image</th>
                    <th class="col name textalign-left">Product Name</th>
                    <th class="col sku textalign-left">SKU</th>
                    <th class="col price textalign-right">Price</th>
                    <th class="col qty textalign-center">Qty</th>
                    <th class="col subtotal textalign-right">Subtotal</th>
                </tr>
                </thead>
                <tbody>
                <tr id="order-item-row-62174" class="order-item-row">
                    <td class="col image textalign-left"><a
                            href="https://www.weltpixel.com/magento2-free-social-login-extension.html"
                            title="Magento 2 Social Login Extension. Facebook Login &amp; Google" tabindex="-1"
                            class="product-item-photo"> <span class="product-image-container product-image-container-97"
                                                              style="width:165px;"><span class="product-image-wrapper"
                                                                                         style="padding-bottom: 100%;"><img
                                        class="product-image-photo lazy"
                                        data-cfsrc="https://www.weltpixel.com/static/version1679594893/frontend/Pearl/weltpixel_custom/en_US/WeltPixel_LazyLoading/images/Loader.gif"
                                        data-original="https://www.weltpixel.com/media/catalog/product/cache/4ec685bd9bc771941eca7a98a8512953/2/1/21_social_login_2_1.png"
                                        data-cfstyle="max-width:50px" width="165" height="165"
                                        alt="Magento 2 Social Login Extension. Facebook Login &amp; Google"
                                        loading="lazy" style="max-width: 100%;"
                                        src="https://www.weltpixel.com/media/catalog/product/cache/4ec685bd9bc771941eca7a98a8512953/2/1/21_social_login_2_1.png"></span></span>
                        </a></td>
                    <td class="col name textalign-left"><a
                            href="https://www.weltpixel.com/magento2-free-social-login-extension.html"
                            title="Magento 2 Social Login Extension. Facebook Login &amp; Google" tabindex="-1"
                            class="product-item-photo"> Magento 2 Social Login Extension. Facebook Login &amp;
                            Google </a>
                        <dl class="item-options">
                            <dt>Downloads</dt>
                            <dd> Magento 2 Social Login, Version 1.11.15 (Mar 22, 2023)<br></dd>
                        </dl>
                    </td>
                    <td class="col sku textalign-left" data-th="SKU">Magento-2-Social-Login-community-0-days</td>
                    <td class="col price textalign-right" data-th="Price"><span class="price-excluding-tax"
                                                                                data-label="Excl. Tax"><span
                                class="cart-price"><span class="price">$0.00</span></span></span></td>
                    <td class="col qty textalign-center" data-th="Qty">
                        <div class="items-qty"><span class="content">1</span></div>
                    </td>
                    <td class="col subtotal textalign-right" data-th="Subtotal"><span class="price-excluding-tax"
                                                                                      data-label="Excl. Tax"><span
                                class="cart-price"><span class="price">$0.00</span></span></span></td>
                </tr>
                <tr id="order-item-row-mobile-62174" class="order-item-row-mobile">
                    <td colspan="2" class="col price textalign-left" data-th="Price"><span class="price-excluding-tax"
                                                                                           data-label="Excl. Tax"><span
                                class="cart-price"><span class="price">$0.00</span></span></span></td>
                    <td colspan="2" class="col qty textalign-center" data-th="Qty">
                        <div class="items-qty"><span class="content">1</span></div>
                    </td>
                    <td colspan="2" class="col subtotal textalign-right" data-th="Subtotal"><span
                            class="price-excluding-tax" data-label="Excl. Tax"><span class="cart-price"><span
                                    class="price">$0.00</span></span></span></td>
                </tr>
                </tbody>
                <tfoot>
                <tr class="subtotal">
                    <th colspan="5" class="mark textalign-right" scope="row">Subtotal</th>
                    <td class="amount textalign-right"><span class="price"><span class="price">$0.00</span></span></td>
                </tr>
                <tr class="grand_total">
                    <th colspan="5" class="mark textalign-right" scope="row"><strong>Grand Total</strong></th>
                    <td class="amount textalign-right"><strong><span class="price"><span
                                    class="price">$0.00</span></span></strong></td>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
