<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

?>
<?php
/**
 * Shopping cart additional info
 * @var $block \Magento\Framework\View\Element\Template
 */
?>
<?php
$name = $block->getNameInLayout();
foreach ($block->getChildNames($name) as $childName) {
    // phpcs:ignore Magento2.Security.LanguageConstruct.DirectOutput
    echo $block->getChildBlock($childName)->setItem($block->getItem())->toHtml();
}
?>

<dl class="item-options"> 
    <dt>Magento Edition</dt>
    <dd> Open Source (Community) </dd> 
    <dt>Support</dt>
    <dd> No Support for free products - Open Source </dd> 
</dl>