<div class="cart-discount">
<div class="reward-container" data-mage-init='{
    "collapsible":{
        "collapsible": true,
        "openedState": "active",
        "active": true
    }}'>
    <div data-role="title" class="title">
        <strong>Apply Reward Points</strong>
    </div>

    <div data-role="content" class="content">
        <div class="title-apply">
            You Have 
            <strong>0</strong> 
            points left, 1 point = $1
        </div>
        <form action="" class="discount-coupon-apply">
            <div class="fieldset reward">
                <div class="field">
                    <div class="control">
                    <input type="text" class="input-text"  name="" value="0" placeholder="Enter reward amount">
                    </div>
                </div>
                <div class="actions-toolbar"> 
                    <div class="primary">
                        <button  class="action primary apply" type="button" value="Apply">
                            <span>Apply</span>
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
</div>


