<div class="floating-father">
    <a id="btn-float">
        <span class="title-animation"><?= $block->escapeHtml(__('How about a gift?')) ?></span>
    </a>

    <div id="modal">
        <div class="container-float">
            <div class="container-float__newlsetter">

                <div class="left-section">
                    <img class="image-fade" alt="Newsletter Fashion Box" data-cfsrc="https://www.weltpixel.com/media/wysiwyg/nsltr-1.png" src="https://www.weltpixel.com/media/wysiwyg/nsltr-1.png">
                </div>
                <div class="answer-section">
                    <div class="answer-section__middle">
                        <div class="title-answer">
                            Answer 5 simple questions and we'll send you a gift :-)
                        </div>

                        <p>
                        <i class="fa-sharp fa-solid fa-lock"></i>
                            This is the only time you'll receive this invitation.
                            <u>You receive a guaranteed gift</u>, in exchange for a quick opinion :-)
                        </p>
                    </div>
                    <div class="answer-section__rigth">
                        <p><strong>TAKE THE SURVEY</strong></p>
                        <a href="" class="btn-float wp-button">
                        <i class="fa-solid fa-gift"></i></i>Start Here
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="action-close" data-role="closeBtn" type="button"></div>
    </div>
</div>

